/** *************************************************************************************
  * Copyright (c) 2024-2025 Beijing Institute of Open Source Chip (BOSC)
  * Copyright (c) 2020-2025 Institute of Computing Technology, Chinese Academy of Sciences
  * Copyright (c) 2020-2021 Peng Cheng Laboratory
  *
  * XiangShan is licensed under Mulan PSL v2.
  * You can use this software according to the terms and conditions of the Mulan PSL v2.
  * You may obtain a copy of Mulan PSL v2 at:
  * http://license.coscl.org.cn/MulanPSL2
  *
  * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
  * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
  * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
  *
  * See the Mulan PSL v2 for more details.
  * *************************************************************************************
  */

package xscache.coupledL2.prefetch

import chisel3._
import chisel3.util._
import freechips.rocketchip.util.ValidPseudoLRU
import org.chipsalliance.cde.config.Parameters
import utility._
import xscache.coupledL2._
import xscache.coupledL2.utils._

/** Store prefetch mini buffer in L2.
  *
  * Store prefetch requests are generated by the L1 when a store is committed into
  * the store buffer, and are forwarded to L2 through the L1->L2 prefetch channel.
  * Since the emitted prefetch request is block granular, requests are merged here
  * by cache block address:
  *
  *  - hit : merge into the existing entry by ORing the byte mask (no new entry,
  *          refresh the replacement state)
  *  - miss: allocate a new entry; the selected victim is sent out as a prefetch
  *          request this cycle (replacement == send, the address is never changed)
  *  - a fully covered block (all mask bits set) does not need the old data, so no
  *    prefetch request is issued for it, the entry is just invalidated
  *  - at most one allocation and one send per cycle
  *
  * This is a smaller "store buffer only for prefetch": it is smaller than the L1
  * store buffer so that entries are replaced (i.e. prefetch requests are sent)
  * earlier, which is where the timeliness of this prefetch comes from.
  */
class StorePrefetchBuffer(implicit p: Parameters) extends PrefetchModule {
  // capacity: 64B * 4, leaving several entries of lead time before the
  // default 9-entry Sbuffer replacement threshold is reached
  val SIZE = 4
  val IN_FIFO_SIZE = 4
  val VICTIM_FIFO_SIZE = 4
  val SHADOW_SIZE = 32
  val AGE_BITS = 16
  val MAX_AGE = (1 << AGE_BITS) - 1

  class StorePrefetchIn extends Bundle {
    // 64B-aligned block address
    val addr = UInt(64.W)
    // byte mask of the block, bit i means byte i of the block is written
    val mask = UInt(64.W)
  }

  class VictimEntry extends Bundle {
    val addr = UInt(64.W)
    val allocAge = UInt(AGE_BITS.W)
  }

  val io = IO(new Bundle {
    val enable = Input(Bool())
    val in = Flipped(ValidIO(new StorePrefetchIn))
    val req = DecoupledIO(new PrefetchReq)
  })

  // 0 / 1: whether to enable
  private val cstEnable = Constantin.createRecord("storePfBuffer_enable" + cacheParams.hartId.toString, initValue = 1)
  val enable = io.enable && cstEnable.orR

  val entries = Reg(Vec(SIZE, UInt(64.W))) // block address, block offset bits are zero
  val masks = Reg(Vec(SIZE, UInt(64.W))) // merged byte mask
  val valids = RegInit(VecInit(Seq.fill(SIZE)(false.B)))
  val allocAge = RegInit(VecInit(Seq.fill(SIZE)(0.U(AGE_BITS.W))))
  val plru = new ValidPseudoLRU(SIZE)

  // FIFO history of recently emitted store prefetches. This is statistics-only
  // state: it never applies backpressure to the prefetch path.
  val shadowEntries = Reg(Vec(SHADOW_SIZE, UInt(64.W)))
  val shadowValids = RegInit(VecInit(Seq.fill(SHADOW_SIZE)(false.B)))
  val shadowEnqPtr = RegInit(0.U(log2Up(SHADOW_SIZE).W))
  val shadowCount = RegInit(0.U(log2Up(SHADOW_SIZE + 1).W))

  // input queue: keep requests when the buffer cannot accept them in this cycle
  val inQ = Module(new Queue(new StorePrefetchIn, IN_FIFO_SIZE))
  inQ.io.enq.valid := io.in.valid && enable
  inQ.io.enq.bits := io.in.bits
  XSPerfAccumulate("store_pf_buf_in_drop", io.in.valid && enable && !inQ.io.enq.ready)

  // victim queue: buffer the blocks which are replaced out and will be sent
  val victimQ = Module(new Queue(new VictimEntry, VICTIM_FIFO_SIZE))

  val inBlock = Cat(inQ.io.deq.bits.addr(inQ.io.deq.bits.addr.getWidth - 1, offsetBits), 0.U(offsetBits.W))
  val hitVec = VecInit((0 until SIZE).map(i => valids(i) && entries(i) === inBlock))
  val hit = hitVec.asUInt.orR
  val hitIdx = OHToUInt(hitVec.asUInt)
  val inputBlock = Cat(io.in.bits.addr(io.in.bits.addr.getWidth - 1, offsetBits), 0.U(offsetBits.W))

  val shadowHit = VecInit((0 until SHADOW_SIZE).map { i =>
    shadowValids(i) && shadowEntries(i) === inputBlock
  }).asUInt.orR

  // Replacement is invalid-first. ValidPseudoLRU.way(valids) selects the oldest
  // valid candidate, so use the invalid mask while there is a free way and fall
  // back to the resident valid entries only when the buffer is full.
  // NOTE: the way returned by ValidPseudoLRU has an unknown width, force it here
  val victimIdx = Wire(UInt(log2Up(SIZE).W))
  val invalidVictim = plru.way(VecInit((0 until SIZE).map(i => !valids(i))).reverse)
  val validVictim = plru.way(VecInit((0 until SIZE).map(i => valids(i))).reverse)
  victimIdx := Mux(invalidVictim._1, invalidVictim._2, validVictim._2)
  val victimValid = valids(victimIdx)
  val victimFull = victimValid && masks(victimIdx).andR

  // a replaced entry has to be sent out, unless the whole block has been written
  val needSendSlot = inQ.io.deq.valid && !hit && victimValid && !victimFull
  val process = inQ.io.deq.valid && (!needSendSlot || victimQ.io.enq.ready)

  inQ.io.deq.ready := process

  // Age each resident entry until it is replaced. The replacement path copies
  // the age into the victim FIFO before resetting the way for the new entry.
  for (entryIdx <- 0 until SIZE) {
    when (valids(entryIdx) && allocAge(entryIdx) =/= MAX_AGE.U) {
      allocAge(entryIdx) := allocAge(entryIdx) + 1.U
    }
  }

  when(process) {
    when(hit) {
      // merge requests of the same block
      masks(hitIdx) := masks(hitIdx) | inQ.io.deq.bits.mask
      plru.access(hitIdx)
    }.otherwise {
      valids(victimIdx) := true.B
      entries(victimIdx) := inBlock
      masks(victimIdx) := inQ.io.deq.bits.mask
      allocAge(victimIdx) := 0.U
      plru.access(victimIdx)
    }
  }

  victimQ.io.enq.valid := process && needSendSlot
  victimQ.io.enq.bits.addr := entries(victimIdx)
  victimQ.io.enq.bits.allocAge := allocAge(victimIdx)

  // send the replaced block as a store prefetch request
  io.req.valid := victimQ.io.deq.valid && enable
  io.req.bits.tag := parseFullAddress(victimQ.io.deq.bits.addr)._1
  io.req.bits.set := parseFullAddress(victimQ.io.deq.bits.addr)._2
  io.req.bits.vaddr.foreach(_ := 0.U)
  // store prefetch is a write prefetch: the block will be fully/partially written
  io.req.bits.needT := true.B
  io.req.bits.source := 0.U // TODO: keep the same convention as the receiver
  io.req.bits.pfSource := MemReqSource.Prefetch2L2Store.id.U
  io.req.bits.cdpPfDepth.foreach(_ := 0.U)
  victimQ.io.deq.ready := io.req.ready && enable

  // Record only requests that were accepted by the downstream prefetch path.
  // The input lookup intentionally observes the pre-update shadow state, so a
  // request cannot hit the entry being inserted in the same cycle.
  when(io.req.fire) {
    shadowEntries(shadowEnqPtr) := victimQ.io.deq.bits.addr
    shadowValids(shadowEnqPtr) := true.B
    shadowEnqPtr := shadowEnqPtr + 1.U
    when(shadowCount =/= SHADOW_SIZE.U) {
      shadowCount := shadowCount + 1.U
    }
  }

  XSPerfAccumulate("store_pf_buf_alloc", process && !hit)
  XSPerfAccumulate("store_pf_buf_merge", process && hit)
  XSPerfAccumulate("store_pf_buf_send", io.req.fire)
  XSPerfAccumulate("store_pf_buf_shadow_hit", io.in.valid && enable && shadowHit)
  XSPerfAccumulate("store_pf_buf_shadow_valid", shadowCount =/= 0.U)
  XSPerfAccumulate("store_pf_buf_full_block_drop", process && !hit && victimFull)
  XSPerfAccumulate("store_pf_buf_in_valid", io.in.valid && enable)
  XSPerfHistogram("store_pf_buf_valid_num", PopCount(valids), true.B, 0, SIZE, 1)
  XSPerfHistogram("store_pf_buf_alloc_to_send_latency", victimQ.io.deq.bits.allocAge, io.req.fire, 0, 128, 4, true, true)
  XSPerfHistogram("store_pf_buf_alloc_to_send_latency", victimQ.io.deq.bits.allocAge, io.req.fire, 128, 512, 16, true, true)
  XSPerfHistogram("store_pf_buf_alloc_to_send_latency", victimQ.io.deq.bits.allocAge, io.req.fire, 512, 4096, 64, true, true)
  XSPerfHistogram("store_pf_buf_alloc_to_send_latency", victimQ.io.deq.bits.allocAge, io.req.fire, 4096, 65536, 4096, true, false)
}
