/** *************************************************************************************
  * Copyright (c) 2024-2025 Beijing Institute of Open Source Chip (BOSC)
  * Copyright (c) 2020-2025 Institute of Computing Technology, Chinese Academy of Sciences
  * Copyright (c) 2020-2021 Peng Cheng Laboratory
  *
  * XiangShan is licensed under Mulan PSL v2.
  * You can use this software according to the terms and conditions of the Mulan PSL v2.
  * You may obtain a copy of Mulan PSL v2 at:
  * http://license.coscl.org.cn/MulanPSL2
  *
  * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
  * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
  * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
  *
  * See the Mulan PSL v2 for more details.
  * *************************************************************************************
  */

package xscache.coupledL2.prefetch

import chisel3._
import chisel3.util._
import freechips.rocketchip.util.ValidPseudoLRU
import org.chipsalliance.cde.config.Parameters
import utility._
import xscache.coupledL2._
import xscache.coupledL2.utils._

/** Store prefetch mini buffer in L2.
  *
  * Store prefetch requests are generated by the L1 when a store is committed into
  * the store buffer, and are forwarded to L2 through the L1->L2 prefetch channel.
  * Since the emitted prefetch request is block granular, requests are merged here
  * by cache block address:
  *
  *  - hit : merge into the existing entry by ORing the byte mask (no new entry,
  *          refresh the replacement state)
  *  - miss: allocate a new entry; the selected victim is sent out as a prefetch
  *          request this cycle (replacement == send, the address is never changed)
  *  - a fully covered block (all mask bits set) does not need the old data, so no
  *    prefetch request is issued for it, the entry is just invalidated
  *  - at most one allocation and one send per cycle
  *
  * This is a smaller "store buffer only for prefetch": it is smaller than the L1
  * store buffer so that entries are replaced (i.e. prefetch requests are sent)
  * earlier, which is where the timeliness of this prefetch comes from.
  */
class StorePrefetchBuffer(implicit p: Parameters) extends PrefetchModule {
  // capacity: 64B * 8, smaller than the L1 store buffer (64B * 16)
  val SIZE = 8
  val IN_FIFO_SIZE = 4
  val VICTIM_FIFO_SIZE = 4

  class StorePrefetchIn extends Bundle {
    // 64B-aligned block address
    val addr = UInt(64.W)
    // byte mask of the block, bit i means byte i of the block is written
    val mask = UInt(64.W)
  }

  val io = IO(new Bundle {
    val enable = Input(Bool())
    val in = Flipped(ValidIO(new StorePrefetchIn))
    val req = DecoupledIO(new PrefetchReq)
  })

  // 0 / 1: whether to enable
  private val cstEnable = Constantin.createRecord("storePfBuffer_enable" + cacheParams.hartId.toString, initValue = 1)
  val enable = io.enable && cstEnable.orR

  val entries = Reg(Vec(SIZE, UInt(64.W))) // block address, block offset bits are zero
  val masks = Reg(Vec(SIZE, UInt(64.W))) // merged byte mask
  val valids = RegInit(VecInit(Seq.fill(SIZE)(false.B)))
  val plru = new ValidPseudoLRU(SIZE)

  // input queue: keep requests when the buffer cannot accept them in this cycle
  val inQ = Module(new Queue(new StorePrefetchIn, IN_FIFO_SIZE))
  inQ.io.enq.valid := io.in.valid && enable
  inQ.io.enq.bits := io.in.bits
  XSPerfAccumulate("store_pf_buf_in_drop", io.in.valid && enable && !inQ.io.enq.ready)

  // victim queue: buffer the blocks which are replaced out and will be sent
  val victimQ = Module(new Queue(UInt(64.W), VICTIM_FIFO_SIZE))

  val inBlock = Cat(inQ.io.deq.bits.addr(inQ.io.deq.bits.addr.getWidth - 1, offsetBits), 0.U(offsetBits.W))
  val hitVec = VecInit((0 until SIZE).map(i => valids(i) && entries(i) === inBlock))
  val hit = hitVec.asUInt.orR
  val hitIdx = OHToUInt(hitVec.asUInt)

  // replacement: always pick the oldest valid way
  // NOTE: the way returned by ValidPseudoLRU has an unknown width, force it here
  val victimIdx = Wire(UInt(log2Up(SIZE).W))
  victimIdx := plru.way(VecInit((0 until SIZE).map(i => valids(i))).reverse)._2
  val victimValid = valids(victimIdx)
  val victimFull = victimValid && masks(victimIdx).andR

  // a replaced entry has to be sent out, unless the whole block has been written
  val needSendSlot = inQ.io.deq.valid && !hit && victimValid && !victimFull
  val process = inQ.io.deq.valid && (!needSendSlot || victimQ.io.enq.ready)

  inQ.io.deq.ready := process

  when(process) {
    when(hit) {
      // merge requests of the same block
      masks(hitIdx) := masks(hitIdx) | inQ.io.deq.bits.mask
      plru.access(hitIdx)
    }.otherwise {
      valids(victimIdx) := true.B
      entries(victimIdx) := inBlock
      masks(victimIdx) := inQ.io.deq.bits.mask
      plru.access(victimIdx)
    }
  }

  victimQ.io.enq.valid := process && needSendSlot
  victimQ.io.enq.bits := entries(victimIdx)

  // send the replaced block as a store prefetch request
  io.req.valid := victimQ.io.deq.valid && enable
  io.req.bits.tag := parseFullAddress(victimQ.io.deq.bits)._1
  io.req.bits.set := parseFullAddress(victimQ.io.deq.bits)._2
  io.req.bits.vaddr.foreach(_ := 0.U)
  // store prefetch is a write prefetch: the block will be fully/partially written
  io.req.bits.needT := true.B
  io.req.bits.source := 0.U // TODO: keep the same convention as the receiver
  io.req.bits.pfSource := MemReqSource.Prefetch2L2Store.id.U
  io.req.bits.cdpPfDepth.foreach(_ := 0.U)
  victimQ.io.deq.ready := io.req.ready && enable

  XSPerfAccumulate("store_pf_buf_alloc", process && !hit)
  XSPerfAccumulate("store_pf_buf_merge", process && hit)
  XSPerfAccumulate("store_pf_buf_send", io.req.fire)
  XSPerfAccumulate("store_pf_buf_full_block_drop", process && !hit && victimFull)
  XSPerfAccumulate("store_pf_buf_in_valid", io.in.valid && enable)
  XSPerfHistogram("store_pf_buf_valid_num", PopCount(valids), true.B, 0, SIZE, 1)
}
